name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build the test stage image from your multi-stage Dockerfile
      - name: Build test image
        run: docker build --target test -t ragchatbot:test .

      # Run unit tests INSIDE the container with API_KEY from Actions secrets.
      # We pass it at runtime (-e), not at build time (safer; nothing baked into the image).
      - name: Run unit tests
        env:
          # Fallback to 'dev' so PRs from forks (which don't get secrets) still pass.
          API_KEY: ${{ secrets.API_KEY != '' && secrets.API_KEY || 'dev' }}
        run: docker run --rm -e API_KEY="${API_KEY}" ragchatbot:test

      # Run Ruff inside the same test image (no secret needed here)
      - name: Run linter
        run: docker run --rm ragchatbot:test /opt/venv/bin/ruff check .
