name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build the test stage (includes pytest + ruff + tests/)
      - name: Build test image
        run: docker build --target test -t ragchatbot:test .

      # Run unit tests (default CMD in test stage already runs pytest -m "not integration")
      - name: Run unit tests
        run: docker run --rm ragchatbot:test

      # Run linter inside the test image
      - name: Run linter
        run: docker run --rm ragchatbot:test ruff check .
