name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Build your image with dev tools (pytest + ruff)
      - name: Build Docker image
        run: docker build -t ragchatbot:ci .

      # Run tests inside the container
      - name: Run unit tests
        run: docker run --rm ragchatbot:ci pytest -m "not integration" -v

      # Run linter inside the container
      - name: Run linter
        run: docker run --rm ragchatbot:ci ruff check .